/**
 * Georgia Tech catalog courses – names, departments, numbers from catalog.gatech.edu/coursesaz/
 * Subset of real courses for seed. Add more by parsing additional department pages.
 */
export interface SeedCourse {
	department: string
	course_number: number
	course_name: string
	description: string | null
	credit_hours: number
}

export const GT_CATALOG_COURSES: SeedCourse[] = [
	// CS – Computer Science
	{ department: 'CS', course_number: 1100, course_name: 'Freshman Leap Seminar', description: 'Small group discussions with first year students.', credit_hours: 1 },
	{ department: 'CS', course_number: 1301, course_name: 'Introduction to Computing', description: 'Introduction to computing principles and programming practices.', credit_hours: 3 },
	{ department: 'CS', course_number: 1315, course_name: 'Introduction to Media Computation', description: 'Introduction to computation in a media and communication context.', credit_hours: 3 },
	{ department: 'CS', course_number: 1331, course_name: 'Introduction to Object Oriented Programming', description: 'Techniques and methods of object-oriented programming.', credit_hours: 3 },
	{ department: 'CS', course_number: 1332, course_name: 'Data Structures and Algorithms for Applications', description: 'Computer data structures and algorithms in the context of OOP.', credit_hours: 3 },
	{ department: 'CS', course_number: 1371, course_name: 'Computing for Engineers', description: 'Foundations of computing with design and analysis of algorithms.', credit_hours: 3 },
	{ department: 'CS', course_number: 2050, course_name: 'Introduction to Discrete Mathematics for Computer Science', description: 'Proof methods, induction, recursion, complexity.', credit_hours: 3 },
	{ department: 'CS', course_number: 2110, course_name: 'Computer Organization and Programming', description: 'Basic computer hardware, machine language, assembly, and C.', credit_hours: 4 },
	{ department: 'CS', course_number: 2200, course_name: 'Computer Systems and Networks', description: 'Computer system structure and networking.', credit_hours: 4 },
	{ department: 'CS', course_number: 2316, course_name: 'Data Manipulation for Science and Industry', description: 'Reading, manipulating, and exporting data.', credit_hours: 3 },
	{ department: 'CS', course_number: 2340, course_name: 'Objects and Design', description: 'Object-oriented methods for large programs.', credit_hours: 3 },
	{ department: 'CS', course_number: 2600, course_name: 'Knowledge Representation and Processing', description: 'Representation and manipulation of symbolic information.', credit_hours: 4 },
	{ department: 'CS', course_number: 2701, course_name: 'Startup Lab: Introduction to Technology Ventures', description: 'Technology venture creation and opportunity identification.', credit_hours: 3 },
	{ department: 'CS', course_number: 3001, course_name: 'Computing, Society, and Professionalism', description: 'Role and impact of ICT in society and ethics.', credit_hours: 3 },
	{ department: 'CS', course_number: 3210, course_name: 'Design of Operating Systems', description: 'OS concepts: multi-threading, scheduling, synchronization.', credit_hours: 3 },
	{ department: 'CS', course_number: 3235, course_name: 'Introduction to Information Security', description: 'Threats, controls, security for OS and networks.', credit_hours: 3 },
	{ department: 'CS', course_number: 3240, course_name: 'Languages and Computation', description: 'Interpreters, scanners, parsers, models of computation.', credit_hours: 3 },
	{ department: 'CS', course_number: 3251, course_name: 'Computer Networking I', description: 'Problems in computer networking and programming.', credit_hours: 3 },
	{ department: 'CS', course_number: 3300, course_name: 'Introduction to Software Engineering', description: 'Team-based software engineering principles.', credit_hours: 3 },
	{ department: 'CS', course_number: 3451, course_name: 'Computer Graphics', description: 'Geometric constructions, transformations, rendering.', credit_hours: 3 },
	{ department: 'CS', course_number: 3510, course_name: 'Design and Analysis of Algorithms', description: 'Design and analysis of efficient algorithms.', credit_hours: 3 },
	{ department: 'CS', course_number: 3600, course_name: 'Introduction to Artificial Intelligence', description: 'AI and machine learning introduction.', credit_hours: 3 },
	{ department: 'CS', course_number: 3630, course_name: 'Introduction to Perception and Robotics', description: 'Computer and robot perception and action.', credit_hours: 3 },
	{ department: 'CS', course_number: 3750, course_name: 'Human Computer Interface Design and Evaluation', description: 'User-system compatibility and human factors.', credit_hours: 3 },
	{ department: 'CS', course_number: 4001, course_name: 'Computing, Society, and Professionalism', description: 'ICT in society, ethics, and public policy.', credit_hours: 3 },
	{ department: 'CS', course_number: 4210, course_name: 'Advanced Operating Systems', description: 'Advanced OS abstractions and implementations.', credit_hours: 3 },
	{ department: 'CS', course_number: 4235, course_name: 'Introduction to Information Security', description: 'Security for OS, databases, networks.', credit_hours: 3 },
	{ department: 'CS', course_number: 4240, course_name: 'Compilers, Interpreters, and Program Analyzers', description: 'Design and implementation of compilers.', credit_hours: 3 },
	{ department: 'CS', course_number: 4245, course_name: 'Introduction to Data Mining and Analysis', description: 'Computational techniques for large datasets.', credit_hours: 3 },
	{ department: 'CS', course_number: 4400, course_name: 'Introduction to Database Systems', description: 'Entity-relationship model, relational DBs, query languages.', credit_hours: 3 },
	{ department: 'CS', course_number: 4476, course_name: 'Introduction to Computer Vision', description: 'Image formation, feature detection, stereo, classification.', credit_hours: 3 },
	{ department: 'CS', course_number: 4510, course_name: 'Automata and Complexity Theory', description: 'Machine models, undecidability, complexity classes.', credit_hours: 3 },
	{ department: 'CS', course_number: 4641, course_name: 'Machine Learning', description: 'Machine learning techniques and applications.', credit_hours: 3 },
	{ department: 'CS', course_number: 4644, course_name: 'Deep Learning', description: 'Neural networks, optimization, applications to AI.', credit_hours: 3 },
	{ department: 'CS', course_number: 4650, course_name: 'Natural Language Understanding', description: 'Systems that comprehend natural language.', credit_hours: 3 },
	// MATH
	{ department: 'MATH', course_number: 1111, course_name: 'College Algebra', description: 'Properties of algebraic, exponential, logarithmic functions.', credit_hours: 4 },
	{ department: 'MATH', course_number: 1113, course_name: 'Pre-calculus', description: 'Basic functions needed for the study of calculus.', credit_hours: 4 },
	{ department: 'MATH', course_number: 1501, course_name: 'Calculus I', description: 'Differential and basic integral calculus.', credit_hours: 4 },
	{ department: 'MATH', course_number: 1551, course_name: 'Differential Calculus', description: 'Differential calculus and limits.', credit_hours: 2 },
	{ department: 'MATH', course_number: 1552, course_name: 'Integral Calculus', description: 'Definite and indefinite integrals, techniques, series.', credit_hours: 4 },
	{ department: 'MATH', course_number: 1553, course_name: 'Introduction to Linear Algebra', description: 'Linear algebra including eigenvalues and eigenvectors.', credit_hours: 2 },
	{ department: 'MATH', course_number: 1554, course_name: 'Linear Algebra', description: 'Eigenvalues, eigenvectors, diagonalization.', credit_hours: 4 },
	{ department: 'MATH', course_number: 1712, course_name: 'Survey of Calculus', description: 'Techniques of differentiation and integration.', credit_hours: 4 },
	{ department: 'MATH', course_number: 2106, course_name: 'Foundations of Mathematical Proof', description: 'Introduction to proofs in advanced mathematics.', credit_hours: 3 },
	{ department: 'MATH', course_number: 2550, course_name: 'Introduction to Multivariable Calculus', description: 'Vectors, curves, functions of several variables.', credit_hours: 2 },
	{ department: 'MATH', course_number: 2551, course_name: 'Multivariable Calculus', description: 'Multivariable calculus and vector analysis.', credit_hours: 4 },
	{ department: 'MATH', course_number: 2552, course_name: 'Differential Equations', description: 'Numerical and analytic solutions of ODEs.', credit_hours: 4 },
	{ department: 'MATH', course_number: 2603, course_name: 'Introduction to Discrete Mathematics', description: 'Logic, induction, counting, graph theory.', credit_hours: 4 },
	{ department: 'MATH', course_number: 3012, course_name: 'Applied Combinatorics', description: 'Combinatorial structures and counting.', credit_hours: 3 },
	{ department: 'MATH', course_number: 3670, course_name: 'Statistics and Applications', description: 'Probability and statistical methods.', credit_hours: 3 },
	// ECE
	{ department: 'ECE', course_number: 1010, course_name: 'Introduction to ECE Design', description: 'Hands-on, team-based activities using robotics.', credit_hours: 2 },
	{ department: 'ECE', course_number: 2020, course_name: 'Digital System Design', description: 'Digital design, Boolean algebra, datapath, assembly.', credit_hours: 3 },
	{ department: 'ECE', course_number: 2026, course_name: 'Introduction to Signal Processing', description: 'Discrete-time signal processing and linear systems.', credit_hours: 3 },
	{ department: 'ECE', course_number: 2031, course_name: 'Digital Design Laboratory', description: 'Design and implementation of digital systems.', credit_hours: 2 },
	{ department: 'ECE', course_number: 2035, course_name: 'Programming for Hardware/Software Systems', description: 'Complex execution and storage mechanisms.', credit_hours: 4 },
	{ department: 'ECE', course_number: 2036, course_name: 'Engineering Software Design', description: 'Object-oriented software for engineering applications.', credit_hours: 4 },
	{ department: 'ECE', course_number: 2040, course_name: 'Circuit Analysis', description: 'DC and AC circuit theory and analysis.', credit_hours: 3 },
	{ department: 'ECE', course_number: 3025, course_name: 'Electromagnetics', description: 'Electromagnetic fields and waves.', credit_hours: 3 },
	{ department: 'ECE', course_number: 3040, course_name: 'Microelectronic Circuits', description: 'Analysis and design of analog circuits.', credit_hours: 3 },
	{ department: 'ECE', course_number: 3050, course_name: 'Systems and Controls', description: 'Linear systems and control theory.', credit_hours: 3 },
	{ department: 'ECE', course_number: 3072, course_name: 'Computer Engineering Software Foundations', description: 'Software foundations for computer engineering.', credit_hours: 3 },
	{ department: 'ECE', course_number: 3710, course_name: 'Computer Design Laboratory', description: 'Design and implementation of computer systems.', credit_hours: 2 },
	{ department: 'ECE', course_number: 3741, course_name: 'Fundamentals of Digital Signal Processing', description: 'Digital signal processing fundamentals.', credit_hours: 3 },
	{ department: 'ECE', course_number: 4100, course_name: 'Advanced Computer Architecture', description: 'Advanced computer organization and architecture.', credit_hours: 3 },
	// ME
	{ department: 'ME', course_number: 1770, course_name: 'Introduction to Engineering Graphics', description: 'Engineering graphics and CAD.', credit_hours: 2 },
	{ department: 'ME', course_number: 2016, course_name: 'Computing Techniques', description: 'Computing and numerical methods for ME.', credit_hours: 3 },
	{ department: 'ME', course_number: 2110, course_name: 'Thermodynamics', description: 'First and second laws, cycles, properties.', credit_hours: 3 },
	{ department: 'ME', course_number: 2202, course_name: 'Dynamics of Rigid Bodies', description: 'Kinematics and kinetics of rigid bodies.', credit_hours: 3 },
	{ department: 'ME', course_number: 3017, course_name: 'System Dynamics and Control', description: 'Modeling and control of dynamic systems.', credit_hours: 3 },
	{ department: 'ME', course_number: 3057, course_name: 'Thermal Systems Design', description: 'Design of thermal and fluid systems.', credit_hours: 3 },
	{ department: 'ME', course_number: 3340, course_name: 'Heat Transfer', description: 'Conduction, convection, radiation.', credit_hours: 3 },
	{ department: 'ME', course_number: 4180, course_name: 'Manufacturing Processes and Systems', description: 'Manufacturing processes and systems.', credit_hours: 3 },
	// PHYS
	{ department: 'PHYS', course_number: 2211, course_name: 'Introductory Physics I', description: 'Mechanics, waves, thermodynamics.', credit_hours: 4 },
	{ department: 'PHYS', course_number: 2212, course_name: 'Introductory Physics II', description: 'Electricity, magnetism, optics.', credit_hours: 4 },
	{ department: 'PHYS', course_number: 2231, course_name: 'Basic Physics I', description: 'Algebra-based mechanics and thermodynamics.', credit_hours: 4 },
	{ department: 'PHYS', course_number: 2232, course_name: 'Basic Physics II', description: 'Algebra-based electricity and magnetism.', credit_hours: 4 },
	// CHEM
	{ department: 'CHEM', course_number: 1211, course_name: 'General Chemistry I', description: 'Atomic structure, bonding, stoichiometry.', credit_hours: 4 },
	{ department: 'CHEM', course_number: 1212, course_name: 'General Chemistry II', description: 'Thermodynamics, kinetics, equilibrium.', credit_hours: 4 },
	{ department: 'CHEM', course_number: 1310, course_name: 'General Chemistry for Engineers', description: 'Chemistry for engineering students.', credit_hours: 4 },
	{ department: 'CHEM', course_number: 2311, course_name: 'Organic Chemistry I', description: 'Structure and reactivity of organic compounds.', credit_hours: 4 },
	{ department: 'CHEM', course_number: 2312, course_name: 'Organic Chemistry II', description: 'Reaction mechanisms and synthesis.', credit_hours: 4 },
	// Other departments – representative courses
	{ department: 'ECON', course_number: 2101, course_name: 'Principles of Microeconomics', description: 'Microeconomic theory and applications.', credit_hours: 3 },
	{ department: 'ECON', course_number: 2102, course_name: 'Principles of Macroeconomics', description: 'Macroeconomic theory and policy.', credit_hours: 3 },
	{ department: 'ENGL', course_number: 1101, course_name: 'English Composition I', description: 'Composition and rhetoric.', credit_hours: 3 },
	{ department: 'ENGL', course_number: 1102, course_name: 'English Composition II', description: 'Research and argumentation.', credit_hours: 3 },
	{ department: 'PSYC', course_number: 1101, course_name: 'General Psychology', description: 'Introduction to psychology.', credit_hours: 3 },
	{ department: 'HTS', course_number: 2080, course_name: 'Science, Technology, and Society', description: 'Historical and social dimensions of technology.', credit_hours: 3 },
	{ department: 'ISYE', course_number: 2027, course_name: 'Probability with Applications', description: 'Probability theory and applications.', credit_hours: 3 },
	{ department: 'ISYE', course_number: 3039, course_name: 'Basic Optimization Methods', description: 'Linear and nonlinear optimization.', credit_hours: 3 },
	{ department: 'MGT', course_number: 2106, course_name: 'Legal and Ethical Environment of Business', description: 'Business law and ethics.', credit_hours: 3 },
	{ department: 'MGT', course_number: 3000, course_name: 'Financial and Managerial Accounting', description: 'Accounting for business decisions.', credit_hours: 3 },
	{ department: 'PUBP', course_number: 3000, course_name: 'US Constitutional Issues', description: 'Constitutional law and policy.', credit_hours: 3 },
	{ department: 'AE', course_number: 1601, course_name: 'Aerospace Engineering Seminar', description: 'Introduction to aerospace engineering.', credit_hours: 1 },
	{ department: 'AE', course_number: 2020, course_name: 'Computational Methods for Aerospace Engineering', description: 'Numerical methods for AE.', credit_hours: 3 },
	{ department: 'CEE', course_number: 2040, course_name: 'Civil Engineering Systems', description: 'Systems approach to civil engineering.', credit_hours: 3 },
	{ department: 'BMED', course_number: 2100, course_name: 'Introduction to Biomedical Engineering', description: 'Introduction to BME.', credit_hours: 3 },
]
