/**
 * Georgia Tech catalog department codes and names from catalog.gatech.edu/coursesaz/
 * Used for accurate department list in seed data.
 */
export const GT_CATALOG_DEPARTMENTS: { code: string; name: string }[] = [
	{ code: 'ACCT', name: 'Accounting' },
	{ code: 'AE', name: 'Aerospace Engineering' },
	{ code: 'APPH', name: 'Applied Physiology' },
	{ code: 'ARBC', name: 'Arabic' },
	{ code: 'ARCH', name: 'Architecture' },
	{ code: 'AS', name: 'Air Force Aerospace Studies' },
	{ code: 'ASE', name: 'Applied Systems Engineering' },
	{ code: 'BC', name: 'Building Construction' },
	{ code: 'BCP', name: 'Building Construction - Professional' },
	{ code: 'BIOL', name: 'Biology' },
	{ code: 'BIOS', name: 'Biological Sciences' },
	{ code: 'BMEJ', name: 'Biomed Engr/Joint Emory PKU' },
	{ code: 'BMED', name: 'Biomedical Engineering' },
	{ code: 'BMEM', name: 'Biomedical Engr/Joint Emory' },
	{ code: 'CEE', name: 'Civil and Environmental Engr' },
	{ code: 'CETL', name: 'Center Enhancement-Teach/Learn' },
	{ code: 'CHBE', name: 'Chemical & Biomolecular Engr' },
	{ code: 'CHEM', name: 'Chemistry' },
	{ code: 'CHIN', name: 'Chinese' },
	{ code: 'COE', name: 'College of Engineering' },
	{ code: 'COA', name: 'College of Architecture' },
	{ code: 'COOP', name: 'Cooperative Work Assignment' },
	{ code: 'COS', name: 'College of Sciences' },
	{ code: 'CP', name: 'City Planning' },
	{ code: 'CS', name: 'Computer Science' },
	{ code: 'CSE', name: 'Computational Science & Engr' },
	{ code: 'CX', name: 'Computational Mod, Sim, & Data' },
	{ code: 'EAS', name: 'Earth and Atmospheric Sciences' },
	{ code: 'ECE', name: 'Electrical & Computer Engr' },
	{ code: 'ECEP', name: 'Elect & Comp Engr-Professional' },
	{ code: 'ECON', name: 'Economics' },
	{ code: 'ENGL', name: 'English' },
	{ code: 'FS', name: 'Foreign Studies' },
	{ code: 'FREE', name: 'Free Elective' },
	{ code: 'FREN', name: 'French' },
	{ code: 'GRMN', name: 'German' },
	{ code: 'GT', name: 'Georgia Tech' },
	{ code: 'GTL', name: 'Georgia Tech Lorraine' },
	{ code: 'HEBW', name: 'Hebrew' },
	{ code: 'HIN', name: 'Hindi' },
	{ code: 'HIST', name: 'History' },
	{ code: 'HS', name: 'Health Systems' },
	{ code: 'HTS', name: 'History, Technology & Society' },
	{ code: 'HUM', name: 'Humanities Elective' },
	{ code: 'IAC', name: 'Ivan Allen College' },
	{ code: 'ID', name: 'Industrial Design' },
	{ code: 'IL', name: 'International Logistics' },
	{ code: 'IMBA', name: 'Intl Executive MBA' },
	{ code: 'INTA', name: 'International Affairs' },
	{ code: 'INTN', name: 'Internship' },
	{ code: 'ISYE', name: 'Industrial & Systems Engr' },
	{ code: 'JAPN', name: 'Japanese' },
	{ code: 'KOR', name: 'Korean' },
	{ code: 'LATN', name: 'Latin' },
	{ code: 'LING', name: 'Linguistics' },
	{ code: 'LMC', name: 'Literature, Media & Comm' },
	{ code: 'LS', name: 'Learning Support' },
	{ code: 'MATH', name: 'Mathematics' },
	{ code: 'ME', name: 'Mechanical Engineering' },
	{ code: 'MGT', name: 'Management' },
	{ code: 'ML', name: 'Modern Languages' },
	{ code: 'MLDR', name: 'Manufacturing Leadership' },
	{ code: 'MOT', name: 'Management of Technology' },
	{ code: 'MP', name: 'Medical Physics' },
	{ code: 'MSE', name: 'Materials Science & Engr' },
	{ code: 'MSL', name: 'Military Science & Leadership' },
	{ code: 'MUSI', name: 'Music' },
	{ code: 'NEUR', name: 'Neuroscience' },
	{ code: 'NRE', name: 'Nuclear & Radiological Engr' },
	{ code: 'NS', name: 'Naval Science' },
	{ code: 'PERS', name: 'Persian' },
	{ code: 'PHIL', name: 'Philosophy' },
	{ code: 'PHYS', name: 'Physics' },
	{ code: 'POL', name: 'Political Science' },
	{ code: 'PORT', name: 'Portuguese' },
	{ code: 'PTFE', name: 'Polymer, Textile and Fiber Eng' },
	{ code: 'PSYC', name: 'Psychology' },
	{ code: 'PUBP', name: 'Public Policy' },
	{ code: 'PUBJ', name: 'Public Policy/Joint GSU PhD' },
	{ code: 'RUSS', name: 'Russian' },
	{ code: 'SCI', name: 'Science' },
	{ code: 'SLS', name: 'Serve Learn Sustain' },
	{ code: 'SOC', name: 'Sociology' },
	{ code: 'SPAN', name: 'Spanish' },
	{ code: 'SS', name: 'Social Science Elective' },
	{ code: 'SWAH', name: 'Swahili' },
	{ code: 'UCGA', name: 'Cross Enrollment' },
	{ code: 'VIP', name: 'Vertically Integrated Project' },
	{ code: 'WOLO', name: 'Wolof' },
]
