/**
 * Seed script: generates SQL to insert Georgia Tech catalog courses,
 * random instructors per department, and sections.
 *
 * Run: npx tsx scripts/seed/run-seed.ts
 * Then run the generated scripts/seed/seed.sql in Supabase SQL Editor,
 * or use: psql $DATABASE_URL -f scripts/seed/seed.sql
 *
 * Requires: migrations 001 and 002 already applied.
 */

import * as fs from 'fs'
import * as path from 'path'
import { randomUUID } from 'crypto'
import { GT_CATALOG_COURSES } from './gt-catalog-courses'
import { generateInstructorNamesForDepartment } from './generate-instructor-names'

const DAY_COMBOS: string[][] = [
	['Monday', 'Wednesday'],
	['Tuesday', 'Thursday'],
	['Monday', 'Wednesday', 'Friday'],
	['Tuesday', 'Thursday'],
	['Friday'],
]
const START_TIMES = ['08:00:00', '09:30:00', '11:00:00', '12:30:00', '14:00:00', '15:30:00']
const SECTION_CODES = ['A', 'B', 'C', 'D']
const BUILDINGS = ['Clough', 'College of Computing', 'Skiles', 'Howey', 'Boggs', 'Van Leer', 'Klaus', 'IC', null]

function pick<T>(arr: T[], seed: number): T {
	return arr[seed % arr.length]
}

function escapeSql(s: string | null): string {
	if (s == null) return 'NULL'
	return "'" + String(s).replace(/'/g, "''") + "'"
}

function main() {
	const departments = new Set(GT_CATALOG_COURSES.map((c) => c.department))
	const instructorNamesByDept = new Map<string, string[]>()
	for (const dept of departments) {
		instructorNamesByDept.set(dept, generateInstructorNamesForDepartment(dept, 6))
	}

	const usedNames = new Set<string>()
	const instructorIdByDeptAndName = new Map<string, string>()
	const instructorRows: { id: string; name: string; department: string }[] = []
	for (const [dept, names] of instructorNamesByDept) {
		for (const name of names) {
			let uniqueName = name
			if (usedNames.has(name)) uniqueName = `${name} (${dept})`
			usedNames.add(uniqueName)
			const id = randomUUID()
			instructorIdByDeptAndName.set(`${dept}:${name}`, id)
			instructorRows.push({ id, name: uniqueName, department: dept })
		}
	}

	const courseIds: string[] = []
	const courseDepts: string[] = []
	const lines: string[] = [
		'-- TechPath seed: Georgia Tech catalog courses, instructors, and sections',
		'-- Generated by scripts/seed/run-seed.ts',
		'-- Source: catalog.gatech.edu/coursesaz/',
		'-- Run once on empty tables. To re-seed: truncate schedule_sections, schedules, sections, courses, instructors (in that order if FKs require), then run this file.',
		'',
		'BEGIN;',
		'',
		'-- Instructors (random names per department)',
	]

	for (const row of instructorRows) {
		lines.push(
			`INSERT INTO instructors (id, name, department, rating, teaching_style) VALUES (${escapeSql(row.id)}, ${escapeSql(row.name)}, ${escapeSql(row.department)}, ${Math.floor(Math.random() * 2) + 4}, NULL);`,
		)
	}

	lines.push('', '-- Courses (from GT catalog)')
	for (const c of GT_CATALOG_COURSES) {
		const id = randomUUID()
		courseIds.push(id)
		courseDepts.push(c.department)
		const desc = c.description ?? ''
		const diff = Math.floor(Math.random() * 2) + 3
		lines.push(
			`INSERT INTO courses (id, department, course_number, course_name, description, credit_hours, difficulty_rating) VALUES (${escapeSql(id)}, ${escapeSql(c.department)}, ${c.course_number}, ${escapeSql(c.course_name)}, ${escapeSql(desc)}, ${c.credit_hours}, ${diff});`,
		)
	}

	lines.push('', '-- Sections (assign random instructors to courses)')
	let crn = 80000
	for (let i = 0; i < GT_CATALOG_COURSES.length; i++) {
		const courseId = courseIds[i]
		const dept = courseDepts[i]
		const instructors = instructorNamesByDept.get(dept) ?? []
		if (instructors.length === 0) continue
		const numSections = 1 + (Math.floor(crn * 7) % 2)
		for (let s = 0; s < numSections; s++) {
			const instName = pick(instructors, crn + s)
			const instructorId = instructorIdByDeptAndName.get(`${dept}:${instName}`)
			if (!instructorId) continue
			const sectionCode = SECTION_CODES[s % SECTION_CODES.length]
			const days = pick(DAY_COMBOS, crn + s + 1)
			const startIdx = (crn + s) % START_TIMES.length
			const startTime = START_TIMES[startIdx]
			const endTime = startIdx + 1 < START_TIMES.length ? START_TIMES[startIdx + 1] : '17:00:00'
			const location = pick(BUILDINGS, crn + s + 2)
			const dayArray = `ARRAY[${days.map((d) => escapeSql(d)).join(', ')}]::day_of_week[]`
			lines.push(
				`INSERT INTO sections (id, course_id, instructor_id, section_code, day_pattern, start_time, end_time, location, crn) VALUES (${escapeSql(randomUUID())}, ${escapeSql(courseId)}, ${escapeSql(instructorId)}, ${escapeSql(sectionCode)}, ${dayArray}, ${escapeSql(startTime)}, ${escapeSql(endTime)}, ${escapeSql(location)}, ${escapeSql(String(crn))});`,
			)
			crn++
		}
	}

	lines.push('', 'COMMIT;')
	const outPath = path.join(__dirname, 'seed.sql')
	fs.writeFileSync(outPath, lines.join('\n'), 'utf-8')
	console.log(`Wrote ${outPath}`)
	console.log(`  Instructors: ${instructorRows.length}`)
	console.log(`  Courses: ${GT_CATALOG_COURSES.length}`)
	console.log(`  Sections: ~${crn - 80000}`)
}

main()
